// Import ponctuel depuis candidator.fr (métadonnées + photo). À réactualiser à la demande
// en modifiant cette liste. familleIdx correspond à l'index dans le tableau des 6 familles
// (0 Gauche radicale, 1 Gauche sociale-démocrate, 2 Bloc central, 3 Droite républicaine,
// 4 Droite nationale, 5 Souverainistes).

const candidatorImg = (filename) => "https://www.candidator.fr/assets/img/candidats/" + encodeURI(filename);

export const CANDIDATOR_IMPORT = [
  ["Nathalie Arthaud", "nathalie_arthaud_presi2027.webp", 0],
  ["François Asselineau", "francois_asselineau_presi2027.webp", 5],
  ["Gabriel Attal", "gabriel_attal_presi2027.webp", 2],
  ["Clémentine Autain", "clementine_autain_presi2027.webp", 0],
  ["Jordan Bardella", "jordan_bardella_presi2027.webp", 4],
  ["Michel Barnier", "michel_barnier_presi2027.webp", 3],
  ["Delphine Batho", "delphine_batho_presi2027.webp", 1],
  ["Xavier Bertrand", "xavier_bertrand_presi2027.webp", 3],
  ["Manuel Bompard", "manuel_bompard_presi2027.webp", 0],
  ["Sébastien Bonnal", "sebastien_bonnal_presi2027.webp", 5],
  ["Élisabeth Borne", "elisabeth_borne_presi2027.webp", 2],
  ["Karim Bouamrane", "karim_bouamrane_presi2027.webp", 1],
  ["Bernard Cazeneuve", "bernard_cazeneuve_presi2027.webp", 1],
  ["Pierre Couchon", "pierre_couchon_presi2027.webp", 2],
  ["Gérald Darmanin", "gerald_darmanin_presi2027.webp", 3],
  ["Dominique de Villepin", "dominique-de-villepin_presi2027.webp", 5],
  ["Nicolas Dupont-Aignan", "nicolas_dupont-aignan_presi2027.webp", 5],
  ["Clara Egger", "clara_egger_presi2027.webp", 5],
  ["Olivier Faure", "olivier_faure_presi2027.webp", 1],
  ["Raphaël Glucksmann", "raphael_glucksmann_presi2027.webp", 1],
  ["Jérôme Guedj", "jerome_guedj_presi2027.webp", 1],
  ["François Hollande", "francois_hollande_presi2027.webp", 1],
  ["Philippe Juvin", "philippe-juvin_presi2027.webp", 3],
  ["Anasse Kazib", "anasse-kazib_presi2027.webp", 0],
  ["Jean-Christophe Lagarde", "jean-christophe-lagarde_presi2027.webp", 2],
  ["Pierre Larrouturou", "pierre-larrouturou_presi2027.webp", 1],
  ["Jean Lassalle", "jean_lassalle_presi2027.webp", 5],
  ["Marine Le Pen", "marine_le pen_presi2027.webp", 4],
  ["Michel-Édouard Leclerc", "michel-edouard_leclerc_presi2027.webp", 5],
  ["David Lisnard", "david_lisnard_presi2027.webp", 3],
  ["Marion Maréchal", "marion_marechal_presi2027.webp", 4],
  ["Lydie Massard", "lydie_massard_presi2027.webp", 1],
  ["Jean-Luc Mélenchon", "jean-luc_melenchon_presi2027.webp", 0],
  ["Antoine Mikolajczak", "antoine_mikolajczak_presi2027.webp", 1],
  ["Alain Mourguy", "alain-mourguy_presi2027.webp", 5],
  ["Valérie Pécresse", "valerie_pecresse_presi2027.webp", 3],
  ["Édouard Philippe", "edouard_philippe_presi2027.webp", 2],
  ["Philippe Herlin", "philippe_herlin_presi2027.webp", 5],
  ["Florian Philippot", "florian-philippot_presi2027.webp", 4],
  ["Jean-Frédéric Poisson", "jean-frederic-poisson_presi2027.webp", 4],
  ["Philippe Poutou", "philippe_poutou_presi2027.webp", 0],
  ["Bruno Retailleau", "bruno_retailleau_presi2027.webp", 3],
  ["Sandrine Rousseau", "sandrine_rousseau_presi2027.webp", 1],
  ["Fabien Roussel", "fabien_roussel_presi2027.webp", 0],
  ["François Ruffin", "françois_ruffin_presi2027.webp", 0],
  ["Patrick Sébastien", "patrick_sebastien_presi2027.webp", 5],
  ["Marine Tondelier", "marine_tondelier_presi2027.webp", 1],
  ["Laurent Wauquiez", "laurent_wauquiez_presi2027.webp", 3],
  ["Éric Zemmour", "eric_zemmour_presi2027.webp", 4],
].map(([nom, file, familleIdx]) => ({ nom, photoUrl: candidatorImg(file), familleIdx }));
